export const refs = {
  mapArea: document.getElementById('map'),
  resizer: document.querySelector('.resizer'),
  randomBtn: document.getElementById('btn-random-place'),
  findMeBtn: document.getElementById('btn-my-coordinate'),
  addMarkerBtn: document.getElementById('btn-add-marker'),
  addLocationbtn: document.getElementById('btn-add-location'),
  addLocationForm: document.getElementById('add-location-form'),
  locationList: document.getElementById('location-list'),
  closeLocationListBtn: document.getElementById('btn-close-location-list'),
  createRouteForm: document.getElementById('create-route-form'),
  userRoutesList: document.getElementById('user-routes'),
  userRouteItemList: document.getElementById('user-route'),
  dialog: document.querySelector('dialog'),
  dialogCloseBtn: document.getElementById('dialog-close-btn'),
  dialogForm: document.getElementById('dialog-form'),
};
